# Generated by Django 4.1.7 on 2023-04-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldCars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcars',
            name='gallery',
        ),
    ]
