# Generated by Django 4.1.7 on 2023-04-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldCars', '0002_remove_worldcars_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldcars',
            old_name='is_pablic',
            new_name='is_pablished',
        ),
    ]
